title: OptMatch
logo:
description: 'This is the detail page of the paper <br><strong><em>OptMatch: Optimized Matchmaking via Modeling the High-Order Interactions on the Arena</em></strong>'
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
paper_link:
data_link: /tree/master/data
